repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: "black"
        name: "Format code (black)"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: "check-yaml"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: "flake8"
        name: "Lint code (flake8)"
        additional_dependencies:
          - "flake8==3.9.2"
          - "flake8-bugbear==21.4.3"
          - "flake8-builtins==1.5.3"
          - "flake8-comprehensions==3.5.0"
          - "flake8-docstrings==1.6.0"
          - "flake8-eradicate==1.1.0"
          - "flake8-mutable==1.2.0"
          - "flake8-pie==0.13.0"
          - "flake8-quotes==3.2.0"
          - "flake8-string-format==0.3.0"
          - "pep8-naming==0.11.1"
        args: [
        "--extend-ignore", "D103,D104,D107",
        "--docstring-convention", "google"]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.5.6
    hooks:
      - id: "sqlfluff-fix"
        name: "SQLFluff Formatter"
      - id: "sqlfluff-lint"
        name: "SQLFluff Linter"
